// Component specs from the musix-ui source (read-only): the component's own doc
// (purpose, usage) + facts extracted from its code — props and defaults, the
// palette tokens it reads, measurements, CSS classes, motion. The composite
// surfaces (player, home, …) are written by hand in surfaces/*.md.
// Usage: node design/components/generate.mjs   (from v2/)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const REPO = new URL('../../../', import.meta.url).pathname;
const UI = REPO + 'frontend/packages/musix-ui/';
const src = readFileSync(UI + 'src/index.jsx', 'utf8');
const starts = [...src.matchAll(/^export (?:function|const) (\w+)/gm)];
let n = 0;
for (let i = 0; i < starts.length; i++) {
  const name = starts[i][1];
  if (!/^[A-Z]/.test(name)) continue;           // hooks and helpers are not components
  const body = src.slice(starts[i].index, i + 1 < starts.length ? starts[i + 1].index : src.length);
  const sig = (body.match(/\(\{([^}]*)\}/) || [, ''])[1].replace(/\s+/g, ' ').trim();
  const uniq = (re) => [...new Set([...body.matchAll(re)].map((m) => m[1]))];
  const tokens = uniq(/\bc\.(\w+)/g);
  const dims = uniq(/\b((?:width|height|size|borderRadius|fontSize|padding|gap|margin|letterSpacing|lineHeight)\s*[:=]\s*[-\d.]+(?:px|em)?)/g);
  const classes = uniq(/(ske-[a-z-]+|brushed-[a-z]+|ob-[a-z-]+|[a-z]+-(?:in|out|pulse|spin)\b)/g);
  const motion = uniq(/(\d+(?:\.\d+)?m?s\s+(?:ease[\w-]*|linear|cubic-bezier\([^)]*\))|cubic-bezier\([^)]*\))/g);
  const docPath = UI + `docs/${name}.md`;
  const doc = existsSync(docPath) ? readFileSync(docPath, 'utf8').replace(/^---[\s\S]*?---\s*/, '').trim() : `# ${name}`;
  const facts = [
    '## From the code (generated)', '',
    `- **Props (defaults):** \`${sig || '—'}\``,
    `- **Palette tokens:** ${tokens.length ? tokens.map((t) => '`' + t + '`').join(', ') : '—'}`,
    `- **Measurements:** ${dims.length ? dims.map((d) => '`' + d + '`').join(', ') : '—'}`,
    `- **CSS classes:** ${classes.length ? classes.map((d) => '`' + d + '`').join(', ') : '—'}`,
    `- **Motion:** ${motion.length ? motion.map((d) => '`' + d + '`').join(', ') : '—'}`,
    '',
    '**States:** see the props (checked, active, loading, disabled, dark/light via `isDark`).',
    'Each client builds this component once in its design system (phase 4/5/7) and is',
    'reviewed against the golden screenshots, not pixel-matched.',
  ];
  writeFileSync(new URL(`${name}.md`, import.meta.url),
    `<!-- GENERATED by design/components/generate.mjs from musix-ui; edit the doc in musix-ui or surfaces/ -->\n${doc}\n\n${facts.join('\n')}\n`);
  n++;
}
console.log(`component specs: ${n}`);
