/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppPlayerRouteImport } from './routes/_app/player'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUploadRouteImport } from './routes/_app/upload'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminAiRouteImport } from './routes/_app/admin/ai'
import { Route as AppAdminInstanceRouteImport } from './routes/_app/admin/instance'
import { Route as AppAdminLibraryRouteImport } from './routes/_app/admin/library'
import { Route as AppAdminOpsRouteImport } from './routes/_app/admin/ops'
import { Route as AppAdminSetupRouteImport } from './routes/_app/admin/setup'
import { Route as AppAlbumIdRouteImport } from './routes/_app/album.$id'
import { Route as AppArtistIdRouteImport } from './routes/_app/artist.$id'
import { Route as AppPlaylistIdRouteImport } from './routes/_app/playlist.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayerRoute = AppPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAiRoute = AppAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminInstanceRoute = AppAdminInstanceRouteImport.update({
  id: '/instance',
  path: '/instance',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLibraryRoute = AppAdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOpsRoute = AppAdminOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSetupRoute = AppAdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAlbumIdRoute = AppAlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppArtistIdRoute = AppArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistIdRoute = AppPlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/import': typeof AppImportRoute
  '/library': typeof AppLibraryRoute
  '/player': typeof AppPlayerRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/admin/ai': typeof AppAdminAiRoute
  '/admin/instance': typeof AppAdminInstanceRoute
  '/admin/library': typeof AppAdminLibraryRoute
  '/admin/ops': typeof AppAdminOpsRoute
  '/admin/setup': typeof AppAdminSetupRoute
  '/album/$id': typeof AppAlbumIdRoute
  '/artist/$id': typeof AppArtistIdRoute
  '/playlist/$id': typeof AppPlaylistIdRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/import': typeof AppImportRoute
  '/library': typeof AppLibraryRoute
  '/player': typeof AppPlayerRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/': typeof AppIndexRoute
  '/admin/ai': typeof AppAdminAiRoute
  '/admin/instance': typeof AppAdminInstanceRoute
  '/admin/library': typeof AppAdminLibraryRoute
  '/admin/ops': typeof AppAdminOpsRoute
  '/admin/setup': typeof AppAdminSetupRoute
  '/album/$id': typeof AppAlbumIdRoute
  '/artist/$id': typeof AppArtistIdRoute
  '/playlist/$id': typeof AppPlaylistIdRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/import': typeof AppImportRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/player': typeof AppPlayerRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/ai': typeof AppAdminAiRoute
  '/_app/admin/instance': typeof AppAdminInstanceRoute
  '/_app/admin/library': typeof AppAdminLibraryRoute
  '/_app/admin/ops': typeof AppAdminOpsRoute
  '/_app/admin/setup': typeof AppAdminSetupRoute
  '/_app/album/$id': typeof AppAlbumIdRoute
  '/_app/artist/$id': typeof AppArtistIdRoute
  '/_app/playlist/$id': typeof AppPlaylistIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/admin'
    | '/import'
    | '/library'
    | '/player'
    | '/search'
    | '/settings'
    | '/upload'
    | '/admin/ai'
    | '/admin/instance'
    | '/admin/library'
    | '/admin/ops'
    | '/admin/setup'
    | '/album/$id'
    | '/artist/$id'
    | '/playlist/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/import'
    | '/library'
    | '/player'
    | '/search'
    | '/settings'
    | '/upload'
    | '/'
    | '/admin/ai'
    | '/admin/instance'
    | '/admin/library'
    | '/admin/ops'
    | '/admin/setup'
    | '/album/$id'
    | '/artist/$id'
    | '/playlist/$id'
    | '/admin'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/admin'
    | '/_app/import'
    | '/_app/library'
    | '/_app/player'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/upload'
    | '/_app/'
    | '/_app/admin/ai'
    | '/_app/admin/instance'
    | '/_app/admin/library'
    | '/_app/admin/ops'
    | '/_app/admin/setup'
    | '/_app/album/$id'
    | '/_app/artist/$id'
    | '/_app/playlist/$id'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/player': {
      id: '/_app/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof AppPlayerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ai': {
      id: '/_app/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AppAdminAiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/instance': {
      id: '/_app/admin/instance'
      path: '/instance'
      fullPath: '/admin/instance'
      preLoaderRoute: typeof AppAdminInstanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/library': {
      id: '/_app/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AppAdminLibraryRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ops': {
      id: '/_app/admin/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AppAdminOpsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/setup': {
      id: '/_app/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AppAdminSetupRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/album/$id': {
      id: '/_app/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AppAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artist/$id': {
      id: '/_app/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof AppArtistIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlist/$id': {
      id: '/_app/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof AppPlaylistIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAiRoute: typeof AppAdminAiRoute
  AppAdminInstanceRoute: typeof AppAdminInstanceRoute
  AppAdminLibraryRoute: typeof AppAdminLibraryRoute
  AppAdminOpsRoute: typeof AppAdminOpsRoute
  AppAdminSetupRoute: typeof AppAdminSetupRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAiRoute: AppAdminAiRoute,
  AppAdminInstanceRoute: AppAdminInstanceRoute,
  AppAdminLibraryRoute: AppAdminLibraryRoute,
  AppAdminOpsRoute: AppAdminOpsRoute,
  AppAdminSetupRoute: AppAdminSetupRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppImportRoute: typeof AppImportRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPlayerRoute: typeof AppPlayerRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumIdRoute: typeof AppAlbumIdRoute
  AppArtistIdRoute: typeof AppArtistIdRoute
  AppPlaylistIdRoute: typeof AppPlaylistIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppImportRoute: AppImportRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPlayerRoute: AppPlayerRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumIdRoute: AppAlbumIdRoute,
  AppArtistIdRoute: AppArtistIdRoute,
  AppPlaylistIdRoute: AppPlaylistIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
