import { chromium } from "@playwright/test";
const out = process.argv[2], theme = process.argv[3] ?? "dark";
const b = await chromium.launch({ channel: "chrome", args: ["--autoplay-policy=no-user-gesture-required"] });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, colorScheme: theme });
const p = await ctx.newPage();
const errors = [];
p.on("pageerror", (e) => errors.push(e.message));
p.on("console", (m) => m.type() === "error" && !m.text().includes("401") && errors.push(m.text()));
await p.goto("http://127.0.0.1:5173/login");
await p.fill("input[type=email]", "mig-owner@example.com");
await p.fill("input[type=password]", "mig-pass-123");
await p.click("button[type=submit]");
await p.waitForURL((u) => !u.pathname.startsWith("/login"));
await p.waitForTimeout(2500);
await p.screenshot({ path: `${out}/home-${theme}.png` });
await p.goto("http://127.0.0.1:5173/library");
await p.waitForFunction(() => document.body.innerText.includes("альбомов") && document.querySelectorAll("img").length > 6, null, { timeout: 60000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/library-${theme}.png` });
await p.goto("http://127.0.0.1:5173/search?q=" + encodeURIComponent("дорога домой"));
await p.waitForTimeout(6000);
await p.screenshot({ path: `${out}/search-${theme}.png` });
await p.goto("http://127.0.0.1:5173/player");
await p.getByRole("button", { name: "Включить поток" }).click();
await p.waitForFunction(() => window.__musix?.usePlayer.getState().playing, null, { timeout: 20000 });
await p.waitForTimeout(3000);
await p.screenshot({ path: `${out}/player-${theme}.png` });
await p.getByRole("button", { name: "Текст песни" }).click();
await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/player-lyrics-${theme}.png` });
console.log("errors", errors);
await b.close();
